name: Firmware Build

on:
  push:
    branches:
      - build-action

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PICO_SDK_URL: https://github.com/raspberrypi/pico-sdk.git
      PICO_SDK_VERSION: 1.3.1
      PICO_DIR: pico-sdk
      ARM_URL_COMMON: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10
      ARM_FILENAME_LINUX: gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      ARM_DIR: arm-toolchain

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Raspberry Pi Pico SDK
        id: cache-pico-sdk
        uses: actions/cache@v3
        with:
          path: deps/${{ env.ARM_DIR }}/
          key: ${{ env.PICO_SDK_URL }}_${{ env.PICO_SDK_VERSION }}

      - name: Clone Raspberry Pi Pico SDK
        if: ${{ steps.cache-pico-sdk.outputs.cache-hit != 'true' }}
        run: |
          mkdir deps
          cd deps
          git clone ${PICO_SDK_URL} -b ${PICO_SDK_VERSION} --depth 1
          cd pico-sdk
          git submodule init
          git submodule update --depth 1

      - name: Cache the ARM toolchain
        id: cache-arm-toolchain
        uses: actions/cache@v3
        with:
          path: deps/${{ env.ARM_DIR }}/
          key: ${{ env.ARM_FILENAME_LINUX }}

      - name: Download the ARM toolchain
        if: ${{ steps.cache-arm-toolchain.outputs.cache-hit != 'true' }}
        run: |
          cd deps
          wget --progress=dot:giga ${ARM_URL_COMMON}/${ARM_FILENAME_LINUX}
          mkdir ${ARM_DIR}
          tar jxf ${ARM_FILENAME_LINUX} --directory ${ARM_DIR} --strip-components 1
          rm ${ARM_FILENAME_LINUX}

      - name: Build
        run: |
          mkdir -p build
          cd build && cmake .. && make
          ls -l
          md5sum alpakka.uf2

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: alpakka
          path: build/alpakka.uf2
