name: Firmware Build

on:
  push:
    branches:
      - build-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import dependency vars
        run: |
          while read line; do
            [[ "$line" == "##"* ]] && break
            [[ "$line" != "" ]] && [[ "$line" != "#"* ]] && echo "$line"
            [[ "$line" != "" ]] && [[ "$line" != "#"* ]] && echo "$line" >> $GITHUB_ENV
          done < scripts/install.sh

      - name: Dependencies from cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: deps/
          key: ${{ env.SDK_URL }}_${{ env.SDK_TAG }}_${{ env.ARM_FILENAME_LINUX }}

      - name: Dependencies from internet
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: make install

      - name: Build
        run: |
          mkdir -p build
          cd build && cmake .. && make
          ls -l
          shasum alpakka.uf2
          echo -e "\
          =================================
          This firmware build was automated
          =================================

          Branch / Tag:
          ${GITHUB_REF}

          Commit:
          ${GITHUB_SHA}

          Checksum (shasum alpakka.uf2):
          $(cat alpakka.uf2 | shasum)

          Job:
          ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          " > metadata.txt

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: alpakka_firmware_artifacts
          path: |
            build/alpakka.uf2
            build/metadata.txt
